In [79]:
import pandas as pd
import unidecode

In [99]:
df = pd.read_csv('results.csv')
df.count()

1                                    171216
2020-03-16 13:55:24.416401           171216
./PEOPLEdata_20200316121225327778    171216
（一九九七年十二月三十一日）                       171215
（ 一九九七年 十二月 三十一日 ）                   171215
（ 一九九七年 十二月 三十一日 ）.1                 171215
dtype: int64

,index,timestamp,identifier,token,ori_seg,des_seg
95904,95887,2020-03-18 10:26:03.982604,./corpora/wiki/processed_20200317103118413533,"soboutrosnomes,comoe","sob outros nomes , como e","sob outros nomes , como e"
95623,95607,2020-03-18 10:24:19.391288,./corpora/wiki/processed_20200317103118413533,paraoexamede,para o exame de,para o exame de
18391,18377,2020-03-18 02:24:02.484743,./corpora/wiki/processed_20200317103118413533,unsdiestimmedejohannsebastianbach.,uns die stimme de johann sebastian bach .,uns diestimme de johann sebastian bach .
43319,43297,2020-03-18 04:58:44.219951,./corpora/wiki/processed_20200317103118413533,policeinterceptoropoliceinterceptoreumaversao,police interceptoro police interceptor e uma v...,police interceptoro police interceptor e uma v...
49766,49742,2020-03-18 05:38:40.17961,./corpora/wiki/processed_20200317103118413533,ortodoxaetiope,ortodoxa etiope,ortodoxa e tiope

In [100]:
df = pd.read_csv('results.csv')

column_dict = dict(zip([x for x in df.columns], ['index', 'timestamp', 'identifier', 'token', 'ori_seg', 'des_seg']))

df = df.rename(columns=column_dict)
df.sample(5)

df = df[df['identifier'].str.contains('./corpora/wiki/processed_20200317103118413533')]
df = df.sort_values('index')
df.head()

,index,timestamp,identifier,token,ori_seg,des_seg
1952,1920,2020-03-18 00:41:58.312901,./corpora/wiki/processed_20200317103118413533,"ashinkaikatana,quee","a shinkai katana , que e","a shinkai katana , que e"
1953,1921,2020-03-18 00:41:58.68985,./corpora/wiki/processed_20200317103118413533,"e60,10metrosdeenvergadura.","e 60 , 10 metros de envergadura .","e 60 , 10 metros de envergadura ."
1954,1922,2020-03-18 00:41:59.063019,./corpora/wiki/processed_20200317103118413533,"alemdisso,osmagostambem","alem disso , os magos tambem","alem disso , os magos tambem"
1955,1923,2020-03-18 00:41:59.435329,./corpora/wiki/processed_20200317103118413533,"quegarethbale,quetambem","que gareth bale , que tambem","que garethbale , que tambem"
1956,1924,2020-03-18 00:41:59.808215,./corpora/wiki/processed_20200317103118413533,dopartidodo,do partido do,do partido do

In [102]:
original_df = pd.read_csv('./corpora/wiki/processed/test.txt', sep='\t', header=None)
original_df = original_df.rename(columns={0: 'token', 1: 'labels'})
original_df.head()

                        token                      labels
0         aShinkaiKatana,queé         sbmmmmmebmmmmesbmes
1  e60,10metrosdeenvergadura.  sbesbebmmmmebebmmmmmmmmmes
2     Alémdisso,osMagostambém     bmmebmmmesbebmmmebmmmme
3     queGarethBale,quetambém     bmebmmmmebmmesbmebmmmme
4                 doPartidodo                 bebmmmmmebe

In [64]:
original_df.count()

token     161692
labels    161692
dtype: int64

In [65]:
df.count()

index         169299
timestamp     169299
identifier    169299
token         169298
ori_seg       169298
des_seg       169298
dtype: int64

In [103]:
original_df['original_token'] = original_df['token']
original_df[['original_token']]
original_df['original_index'] = original_df.index
original_df

,token,labels,original_token,original_index
0,"aShinkaiKatana,queé",sbmmmmmebmmmmesbmes,"aShinkaiKatana,queé",0
1,"e60,10metrosdeenvergadura.",sbesbebmmmmebebmmmmmmmmmes,"e60,10metrosdeenvergadura.",1
2,"Alémdisso,osMagostambém",bmmebmmmesbebmmmebmmmme,"Alémdisso,osMagostambém",2
3,"queGarethBale,quetambém",bmebmmmmebmmesbmebmmmme,"queGarethBale,quetambém",3
4,doPartidodo,bebmmmmmebe,doPartidodo,4
...,...,...,...,...
161687,"Tempo""(Warner)gravou",bmmmessbmmmmesbmmmme,"Tempo""(Warner)gravou",161687
161688,interpretadaem,bmmmmmmmmmmebe,interpretadaem,161688
161689,de1962)éumex-jogadordebeisebol,bebmmessbebesbmmmmmebebmmmmmme,de1962)éumex-jogadordebeisebol,161689
161690,dedireçãodeGoldhaberanteriormenteeramapenas,bebmmmmmebebmmmmmmmebmmmmmmmmmmmebmmebmmmme,dedireçãodeGoldhaberanteriormenteeramapenas,161690
161691,elogoalembrançadafomeficou,sbmmesbmmmmmmmebebmmebmmme,elogoalembrançadafomeficou,161691

In [101]:
df = df.reset_index()
df['new_index'] = df.index
df[['new_index', 'token', 'ori_seg', 'des_seg']]

,new_index,token,ori_seg,des_seg
0,0,"ashinkaikatana,quee","a shinkai katana , que e","a shinkai katana , que e"
1,1,"e60,10metrosdeenvergadura.","e 60 , 10 metros de envergadura .","e 60 , 10 metros de envergadura ."
2,2,"alemdisso,osmagostambem","alem disso , os magos tambem","alem disso , os magos tambem"
3,3,"quegarethbale,quetambem","que gareth bale , que tambem","que garethbale , que tambem"
4,4,dopartidodo,do partido do,do partido do
...,...,...,...,...
169294,169294,"tempo""(warner)gravou","tempo "" ( warner ) gravou","tempo "" ( warner ) gravou"
169295,169295,interpretadaem,interpretada em,interpretada em
169296,169296,de1962)eumex-jogadordebeisebol,de 1962 ) e um ex - jogador de beisebol,de 1962 ) e um ex - jogador de beisebol
169297,169297,dedirecaodegoldhaberanteriormenteeramapenas,de direcao de goldhaber anteriormente eram apenas,de direcao de gold haber anteriormente eram ap...
169298,169298,elogoalembrancadafomeficou,e logo a lembranca da fome ficou,e logo alembrancada fome ficou

In [115]:
original_df.merge(df, how='outer', left_on='original_index', right_on='new_index').head(16000)

,token_x,labels,original_token,original_index,level_0,index,timestamp,identifier,token_y,ori_seg,des_seg,new_index
0,"aShinkaiKatana,queé",sbmmmmmebmmmmesbmes,"aShinkaiKatana,queé",0.0,1952,1920,2020-03-18 00:41:58.312901,./corpora/wiki/processed_20200317103118413533,"ashinkaikatana,quee","a shinkai katana , que e","a shinkai katana , que e",0
1,"e60,10metrosdeenvergadura.",sbesbebmmmmebebmmmmmmmmmes,"e60,10metrosdeenvergadura.",1.0,1953,1921,2020-03-18 00:41:58.68985,./corpora/wiki/processed_20200317103118413533,"e60,10metrosdeenvergadura.","e 60 , 10 metros de envergadura .","e 60 , 10 metros de envergadura .",1
2,"Alémdisso,osMagostambém",bmmebmmmesbebmmmebmmmme,"Alémdisso,osMagostambém",2.0,1954,1922,2020-03-18 00:41:59.063019,./corpora/wiki/processed_20200317103118413533,"alemdisso,osmagostambem","alem disso , os magos tambem","alem disso , os magos tambem",2
3,"queGarethBale,quetambém",bmebmmmmebmmesbmebmmmme,"queGarethBale,quetambém",3.0,1955,1923,2020-03-18 00:41:59.435329,./corpora/wiki/processed_20200317103118413533,"quegarethbale,quetambem","que gareth bale , que tambem","que garethbale , que tambem",3
4,doPartidodo,bebmmmmmebe,doPartidodo,4.0,1956,1924,2020-03-18 00:41:59.808215,./corpora/wiki/processed_20200317103118413533,dopartidodo,do partido do,do partido do,4
...,...,...,...,...,...,...,...,...,...,...,...,...
15995,"=onde""φ""",sbmmesss,"=onde""φ""",15995.0,17934,17915,2020-03-18 02:21:10.914427,./corpora/wiki/processed_20200317103118413533,elecriouaposdamorteda,ele criou apos da morte da,ele criou apos da morte da,15995
15996,desenhadoporSirWilliamHenryWhiteem1888.,bmmmmmmmebmebmebmmmmmebmmmebmmmebebmmes,desenhadoporSirWilliamHenryWhiteem1888.,15996.0,17935,17916,2020-03-18 02:21:11.285665,./corpora/wiki/processed_20200317103118413533,"jardimfabiolaieii,jardimaquarius,barro","jardim fabiola i e ii , jardim aquarius , barro","jardim fabiolaie ii , jardim aquarius , barro",15996
15997,apoiodeEspartaedeCorinto.,bmmmebebmmmmmesbebmmmmmes,apoiodeEspartaedeCorinto.,15997.0,17936,17917,2020-03-18 02:21:11.656519,./corpora/wiki/processed_20200317103118413533,naturaisevocavamaimagemdoparaiso,naturais evocavam a imagem do paraiso,naturais evocavam a imagem do paraiso,15997
15998,"entreduasequatrodivisõesdeinfantaria,uma",bmmmebmmesbmmmmebmmmmmmebebmmmmmmmmesbme,"entreduasequatrodivisõesdeinfantaria,uma",15998.0,17937,17918,2020-03-18 02:21:12.029137,./corpora/wiki/processed_20200317103118413533,suaversaofavoritadequalquerumade,sua versao favorita de qualquer uma de,sua versao favorita de qualquer uma de,15998
15999,eolhos,sbmmme,eolhos,15999.0,17938,17919,2020-03-18 02:21:12.400546,./corpora/wiki/processed_20200317103118413533,thesignoffour(1923)the,the sign of four ( 1923 ) the,the sign of four ( 1923 ) the,15999